### ISSUE TITLE
Issue with SLURM RD state 

### ISSUE THREAD

**Issue by zakmachachi** [Matgenix/QToolKit#37]
Dear Developers,

I am using jobflow remote and I recieve the following error:

```
(BAM-remote) [sedm6197@chromite ~]$ jf project check -w example_worker --errors
The selected project is test_project from config file /u/vld/sedm6197/.jfremote/test_project.yaml
x Worker example_worker
Errors:
Worker example_worker
Error while testing worker:
 Traceback (most recent call last):
  File "/u/vld/sedm6197/miniconda3/envs/BAM-remote/lib/python3.10/site-packages/qtoolkit/io/slurm.py", line 412, in parse_jobs_list_output
    slurm_job_state = SlurmState(job_state_string)
  File "/u/vld/sedm6197/miniconda3/envs/BAM-remote/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/u/vld/sedm6197/miniconda3/envs/BAM-remote/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 'RD' is not a valid SlurmState

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/u/vld/sedm6197/miniconda3/envs/BAM-remote/lib/python3.10/site-packages/jobflow_remote/config/helper.py", line 158, in check_worker
    qm.get_jobs_list()
  File "/u/vld/sedm6197/miniconda3/envs/BAM-remote/lib/python3.10/site-packages/jobflow_remote/remote/queue.py", line 226, in get_jobs_list
    return self.scheduler_io.parse_jobs_list_output(
  File "/u/vld/sedm6197/miniconda3/envs/BAM-remote/lib/python3.10/site-packages/qtoolkit/io/slurm.py", line 415, in parse_jobs_list_output
    raise OutputParsingError(msg)
qtoolkit.core.exceptions.OutputParsingError: Unknown job state RD for job id 5619126
```

I see it is not yet supported, is this an easy fix? My cluster will only give me this after multiple tries.

Thanks

**Comment by ml-evs** [comment]
Hi @zakmachachi, that looks like quite an obscure state... do jobs run normally without jobflow remote, and have other jobs run successfully with jobflow remote? You could test this by logging onto the machine, going to the work directory for that job and replacing the line like `jf execution run...` with a simple statement "ls" or whatever to see if it is a problem with your account.

The state (according to https://slurm.schedmd.com/squeue.html#OPT_RD--RESV_DEL_HOLD) means "Job is being held after requested reservation was deleted." What that quite means, I don't know... could you also provide the output of `scontrol show job=5619126` as that might give us more to go on.

If it is simply a case of announcing this state to QToolKit then it should be straightforward, but perhaps this instead hints at some kind of incompatibility between jobflow-remote, your config and your cluster.

**Comment by ml-evs** [comment]
Probably @davidwaroquiers knows best here regarding the Slurm states; what should happen in QToolkit when you run into a weird state, presumably it should be let through? RD is mentioned in the comments here but is not included in the list of "important states".

**Comment by zakmachachi** [comment]
Thanks for your quick reply. Weirdly, I came back and ran the check again and it seems to be running fine now.. I've had a look at the scontrol output and got the following from that jobid:

```
(jobflow_remote) (venv_june23) zem@ln02:/mnt/lustre/a2fs-work3/work/e89/e89/zem> scontrol show job=5619126
JobId=5619126 JobName=42cn1m1
   UserId=lebouede(46977) GroupId=n02(1026) MCS_label=N/A
   Priority=0 Nice=0 Account=n02-weat QOS=reservation
   JobState=CANCELLED Reason=JobHeldAdmin Dependency=afterok:5610928(failed)
   Requeue=0 Restarts=0 BatchFlag=1 Reboot=0 ExitCode=0:0
   RunTime=00:00:00 TimeLimit=1-00:00:00 TimeMin=N/A
   SubmitTime=2024-02-20T12:38:29 EligibleTime=Unknown
   AccrueTime=Unknown
   StartTime=2024-02-21T13:49:47 EndTime=2024-02-21T13:49:47 Deadline=N/A
   SuspendTime=None SecsPreSuspend=0 LastSchedEval=2024-02-20T12:38:29 Scheduler=Main
   Partition=standard AllocNode:Sid=ln01:258996
   ReqNodeList=(null) ExcNodeList=(null)
   NodeList=
   NumNodes=3 NumCPUs=320 NumTasks=320 CPUs/Task=1 ReqB:S:C:T=0:0:*:1
   TRES=cpu=320,mem=222G,node=1,billing=320
   Socks/Node=* NtasksPerN:B:S:C=0:0:*:* CoreSpec=*
   MinCPUsNode=1 MinMemoryNode=0 MinTmpDiskNode=0
   Features=(null) DelayBoot=00:00:00
   OverSubscribe=NO Contiguous=0 Licenses=(null) Network=(null)
   Command=/mnt/lustre/a2fs-work2/work/n02/n02/lebouede/SIM/42cn1m1/run/run_wrf_archer.slurm
   WorkDir=/mnt/lustre/a2fs-work2/work/n02/n02/lebouede/SIM/42cn1m1/run
   StdErr=/mnt/lustre/a2fs-work2/work/n02/n02/lebouede/SIM/42cn1m1/run/42cn1m1.5619126.out
   StdIn=/dev/null
   StdOut=/mnt/lustre/a2fs-work2/work/n02/n02/lebouede/SIM/42cn1m1/run/42cn1m1.5619126.out
   Power=
```

This doesn't look my user so I'm not entirely sure whats happened. Either way at least it's from the cluster side. If this does happen again, is there a way to catch this since I have seen this code a few times on this HPC.

**Comment by gpetretto** [comment]
Hi @zakmachachi, indeed this means that there were some jobs on the cluster with that state. I am adding all the existing states to the list, so it should not happen again.

**Comment by ml-evs** [comment]
Glad it's working, that is slightly weird that it's not your job! Perhaps somewhere something is calling `squeue` without it being properly filtered by user, and the parser is simply getting confused. We can leave this issue open to try to debug, I don't see any reason not to add all possible Slurm states as "options" but then do nothing with most of them.

EDIT: perfect timing by @gpetretto :)

**Comment by zakmachachi** [comment]
Amazing, thank you both! Let me know if there is anything further I can do to help!

**Comment by gpetretto** [comment]
The project check calls `qm.get_jobs_list()`, that does not specify any user, so it is equivalent to (roughly) just `squeue`. From my experience in some clusters this returns the jobs of all the users, in others only your jobs. We can think of adding the user name in the check in jobflow-remote, but likely the user will have no job running and having some jobs parsed could also be positive to check that you selected the correct worker type. Not sure what would be better.

**Comment by zakmachachi** [comment]
Ah interesting. Yes, on this cluster `squeue` returns _all_ jobs from all users. In the project config `.yaml` the user is specified (I believe) so this could be passed perhaps?

**Comment by gpetretto** [comment]
I have merged the changes with the additional SLURM states. 
Thinking again about the checks in jobflow-remote, it is not obvious that the user will be defined. For example it will never be defined for a shell worker. But even for remote workers, I define my connection in my `~/.ssh/config` file, so the jfremote configuration does not contain the username. I am afraid that adding some workaround to determine the user may give rise other kind of failures. 
I will close this for the moment, but feel free to reopen if the issue emerges again.

**Comment by ml-evs** [comment]
> I have merged the changes with the additional SLURM states. Thinking again about the checks in jobflow-remote, it is not obvious that the user will be defined. For example it will never be defined for a shell worker. But even for remote workers, I define my connection in my `~/.ssh/config` file, so the jfremote configuration does not contain the username. I am afraid that adding some workaround to determine the user may give rise other kind of failures. I will close this for the moment, but feel free to reopen if the issue emerges again.

Just a minor note that might be helpful for future reference, you can use `squeue --me` to get the logged in user's jobs without having access to the username directly (I think this is universal).

**Comment by gpetretto** [comment]
Nice! Thanks for pointing that out.
