### ISSUE TITLE
`process_placement` unused by `slurm.py`?

### ISSUE THREAD

**Issue by janosh** [Matgenix/QToolKit#47]
i might be missing something but it seems like specifying `process_placement` has no effect on the generated `slurm` submission script. it's sole occurrence is in the supported keys list. it doesn't appear in the parent class `BaseSchedulerIO`

https://github.com/Matgenix/qtoolkit/blob/df856926877b1c7f038919887799e17241d53f07/src/qtoolkit/io/slurm.py#L610-L624

**Comment by gpetretto** [comment]
In `_convert_qresources` there is a call to `resources.get_processes_distribution()` https://github.com/Matgenix/qtoolkit/blob/df856926877b1c7f038919887799e17241d53f07/src/qtoolkit/io/slurm.py#L584. There the `process_placement` is taken into account.
Did you experience issues trying to set the `process_placement`?

**Comment by janosh** [comment]
sorry, i missed that. i had issues without unconstrained placement so added `nodes=1` before realizing that `process_placement` even exists so wanted to look at how that's implemented before giving it a try but evidently didn't look carefully enough since i didn't find it. my bad! 😅
