### ISSUE TITLE
Confusing SLURM template variables

### ISSUE THREAD

**Issue by gpetretto** [Matgenix/QToolKit#48]
More than one person found difficult to identify how to set the resources in jobflow-remote for SLURM keywords. Typically they would try passing something like `ntasks-per-node` instead of `ntasks_per_node`, resulting in an error just stating that the value is not in the template. 
Basically all the options are set using an underscore, making them different from the actual SLURM variables:
https://github.com/Matgenix/qtoolkit/blob/df856926877b1c7f038919887799e17241d53f07/src/qtoolkit/io/slurm.py#L150-L176

I think it would be good to make this smoother for the users. Two possible solutions: 
* accepting both options (e.g. by replacing `-` with `_`), but this may be dangerous
* if `extra` are present in the check: https://github.com/Matgenix/qtoolkit/blob/df856926877b1c7f038919887799e17241d53f07/src/qtoolkit/io/base.py#L86 test if the variable with `_` instead of `-` would be fine and return a more informative error. For example "`ntasks-per-node` is not present in the template, you might want to use `ntasks_per_node`"

Other suggestions?

**Comment by davidwaroquiers** [comment]
Indeed, sounds reasonable to ease the life of the users. Already having the more informative error would be nice.

What would you see as dangerous to accept both - and _ ?
